# -*- coding: utf-8 -*-
"""Apoyo_MCA3_25-1_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoEDp_PaRABGnvsrjIGdTovaGWndAiCv

#**MCA 3**


## Material de apoyo para las clases

Aquí apareceracódigo que se utiliza en clase y que no es en si mismo un programa independiente

---
Editor: Roberto Méndez

Modificado: 13 Sep 24 v1

## Cornu's Spiral

Fresnel Fuctions

Clase: 13 Sep 23 <br>
Tema:  
* Longitud de Arco - Repaso
* Tamaño de paso  / Partición.
  * Cambia *t* de -8pi a 8pi ¿Qué notas en la gráfica?
  * Usa el atributo, n=10000 ¿Qué cambio se ve?
"""

from sympy import symbols, cos, sin,  pi, integrate
from sympy import plot_parametric
t, x = symbols('t x')
def f(t):
  return integrate(cos(pi*x**2/2), (x, 0, t ))
def g(t):
  return integrate(sin(pi*x**2/2), (x, 0, t ))

plot_parametric(f(t), g(t), (t, -4*pi, 4*pi),
                line_color='orange');